/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.crud;
import POJO.Adres;
import dao.AdresDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
/**
 *
 * @author 35747
 */
public class AddressCreator extends javax.swing.JFrame {

    /**
     * Creates new form categoryCreator
     */
    public AddressCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTable = new javax.swing.JTable();
        addAddress = new javax.swing.JButton();
        recordAddress = new javax.swing.JButton();
        deleteAddress = new javax.swing.JButton();
        cityLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        readAddress = new javax.swing.JButton();
        streetLabel = new javax.swing.JLabel();
        postalCodeField = new javax.swing.JTextField();
        houseNrLabel = new javax.swing.JLabel();
        postalCodeLabel = new javax.swing.JLabel();
        houseNrField = new javax.swing.JTextField();
        streetField = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "miasto", "ulica", "kodPocztowy", "nrDomu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AddressTable.setColumnSelectionAllowed(true);
        AddressTable.setShowGrid(true);
        AddressTable.getTableHeader().setReorderingAllowed(false);
        AddressTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddressTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AddressTable);
        AddressTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (AddressTable.getColumnModel().getColumnCount() > 0) {
            AddressTable.getColumnModel().getColumn(0).setResizable(false);
            AddressTable.getColumnModel().getColumn(1).setResizable(false);
            AddressTable.getColumnModel().getColumn(2).setResizable(false);
            AddressTable.getColumnModel().getColumn(3).setResizable(false);
            AddressTable.getColumnModel().getColumn(4).setResizable(false);
        }

        addAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizard.png"))); // NOI18N
        addAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddressActionPerformed(evt);
            }
        });

        recordAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support.png"))); // NOI18N
        recordAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordAddressActionPerformed(evt);
            }
        });

        deleteAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        deleteAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAddressActionPerformed(evt);
            }
        });

        cityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cityLabel.setText("Miasto");

        cityField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        readAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        readAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAddressActionPerformed(evt);
            }
        });

        streetLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        streetLabel.setText("Ulica");

        postalCodeField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        houseNrLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        houseNrLabel.setText("Nr domu");

        postalCodeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        postalCodeLabel.setText("Kod pocztowy");

        houseNrField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        streetField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(cityLabel))
                            .addComponent(streetLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streetField)
                            .addComponent(cityField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addAddress)
                        .addGap(18, 18, 18)
                        .addComponent(recordAddress)
                        .addGap(18, 18, 18)
                        .addComponent(readAddress)
                        .addGap(18, 18, 18)
                        .addComponent(deleteAddress)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postalCodeLabel)
                            .addComponent(houseNrLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(houseNrField)
                            .addComponent(postalCodeField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLabel)
                    .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCodeLabel)
                    .addComponent(postalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(houseNrLabel)
                    .addComponent(houseNrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAddress)
                            .addComponent(recordAddress)))
                    .addComponent(readAddress, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddressActionPerformed
        try {
            if((cityField.getText().isEmpty() || streetField.getText().isEmpty() || postalCodeField.getText().isEmpty() || houseNrField.getText().isEmpty()))
            {
                JOptionPane.showMessageDialog(this, "Pola nie mogą być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(!Pattern.matches("[a-zA-Z]*", cityField.getText())){
                JOptionPane.showMessageDialog(this, "Miasto może zawierać tylko litery.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }            
            else{
                AdresDAO adr = new AdresDAO();
                adr.createAddress(cityField.getText(), streetField.getText(), postalCodeField.getText(), houseNrField.getText());
                AddressTable.setModel(dtm(adr.readAddress()));
            }
        } catch (Exception ex) {
            Logger.getLogger(AddressCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addAddressActionPerformed

    private void recordAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordAddressActionPerformed
        // TODO add your handling code here:
        try {
            if(AddressTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go zmodyfikować.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                AdresDAO adr = new AdresDAO();
                int selectedRow = AddressTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)AddressTable.getModel();
                int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                adr.updateAddress(id, cityField.getText(), streetField.getText(), postalCodeField.getText(), houseNrField.getText());
                AddressTable.setModel(dtm(adr.readAddress()));
            }
        } catch (Exception ex) {
            Logger.getLogger(AddressCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordAddressActionPerformed

    private void deleteAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAddressActionPerformed
        // TODO add your handling code here:
        try {
            if(AddressTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go usunąć.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                AdresDAO adr = new AdresDAO();
                int selectedRow = AddressTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)AddressTable.getModel();
                int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                adr.deleteAddress(id);
                AddressTable.setModel(dtm(adr.readAddress()));
            }
        } catch (Exception ex) {
            Logger.getLogger(AddressCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteAddressActionPerformed

    private void readAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAddressActionPerformed
        // TODO add your handling code here:
        try {
            AdresDAO adr = new AdresDAO();
            AddressTable.setModel(dtm(adr.readAddress()));
        } catch (Exception ex) {
            Logger.getLogger(AddressCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readAddressActionPerformed

    private void AddressTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddressTableMouseClicked
        // TODO add your handling code here:
            int selectedRow = AddressTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)AddressTable.getModel();
            String text1 = (String)dt.getValueAt(selectedRow,1);
            String text2 = (String)dt.getValueAt(selectedRow,2);
            String text3 = (String)dt.getValueAt(selectedRow,3);
            String text4 = (String)dt.getValueAt(selectedRow,4);
            
            cityField.setText(text1);
            streetField.setText(text2);
            postalCodeField.setText(text3);
            houseNrField.setText(text4);
    }//GEN-LAST:event_AddressTableMouseClicked

    private DefaultTableModel dtm(List<Adres> adr){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); 
        String[] propNames = sessionFactory.getClassMetadata(Adres.class).getPropertyNames();
        ArrayList<String> arrL = new ArrayList<String>();
        arrL.add(sessionFactory.getClassMetadata(Adres.class).getIdentifierPropertyName());
        for(int i=0; i<propNames.length; i++){
            arrL.add(propNames[i]);
        }
        String[] columnNames = arrL.toArray(new String[0]);
        DefaultTableModel tab = new DefaultTableModel(columnNames, 0);
        for(Adres a:adr){
            String[] row = {String.valueOf(a.getId()), a.getMiasto(), a.getUlica(), a.getKodPocztowy(), a.getNumerDomu()};
            tab.addRow(row);
        }
        return tab;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddressCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AddressTable;
    private javax.swing.JButton addAddress;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton deleteAddress;
    private javax.swing.JTextField houseNrField;
    private javax.swing.JLabel houseNrLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField postalCodeField;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JButton readAddress;
    private javax.swing.JButton recordAddress;
    private javax.swing.JTextField streetField;
    private javax.swing.JLabel streetLabel;
    // End of variables declaration//GEN-END:variables
}
