/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.crud;
import POJO.Autor;
import POJO.Wydawnictwo;
import dao.AutorDAO;
import static dao.DAO.getSession;
import dao.DAO;
import dao.KategoriaDAO;
import dao.WydawnictwoDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import org.hibernate.annotations.Source;
import org.hibernate.cfg.Configuration;
import static util.HibernateUtil.getSessionFactory;
/**
 *
 * @author 35747
 */
public class PublisherCreator extends javax.swing.JFrame {

    /**
     * Creates new form categoryCreator
     */
    public PublisherCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        publisherTable = new javax.swing.JTable();
        addPublisher = new javax.swing.JButton();
        recordPublisher = new javax.swing.JButton();
        deletePublisher = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        readPublisher = new javax.swing.JButton();
        cityLabel = new javax.swing.JLabel();
        regonField = new javax.swing.JTextField();
        nipLabel = new javax.swing.JLabel();
        regonLabel = new javax.swing.JLabel();
        nipField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        publisherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nazwa", "miasto", "REGON", "NIP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        publisherTable.setColumnSelectionAllowed(true);
        publisherTable.setShowGrid(true);
        publisherTable.getTableHeader().setReorderingAllowed(false);
        publisherTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                publisherTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(publisherTable);
        publisherTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (publisherTable.getColumnModel().getColumnCount() > 0) {
            publisherTable.getColumnModel().getColumn(0).setResizable(false);
            publisherTable.getColumnModel().getColumn(1).setResizable(false);
            publisherTable.getColumnModel().getColumn(2).setResizable(false);
            publisherTable.getColumnModel().getColumn(3).setResizable(false);
            publisherTable.getColumnModel().getColumn(4).setResizable(false);
        }

        addPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizard.png"))); // NOI18N
        addPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPublisherActionPerformed(evt);
            }
        });

        recordPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support.png"))); // NOI18N
        recordPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordPublisherActionPerformed(evt);
            }
        });

        deletePublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        deletePublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePublisherActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setText("Nazwa");

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        readPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        readPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readPublisherActionPerformed(evt);
            }
        });

        cityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cityLabel.setText("Miasto");

        regonField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nipLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nipLabel.setText("NIP");

        regonLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regonLabel.setText("REGON");

        nipField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cityField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(nameLabel))
                            .addComponent(cityLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityField)
                            .addComponent(nameField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPublisher)
                        .addGap(18, 18, 18)
                        .addComponent(recordPublisher)
                        .addGap(18, 18, 18)
                        .addComponent(readPublisher)
                        .addGap(18, 18, 18)
                        .addComponent(deletePublisher)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regonLabel)
                            .addComponent(nipLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nipField)
                            .addComponent(regonField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regonLabel)
                    .addComponent(regonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nipLabel)
                    .addComponent(nipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deletePublisher, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPublisher)
                            .addComponent(recordPublisher)))
                    .addComponent(readPublisher, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPublisherActionPerformed
        try {
            WydawnictwoDAO wyd = new WydawnictwoDAO();
            wyd.createPublisher(nameField.getText(), cityField.getText(), regonField.getText(), nipField.getText());
            publisherTable.setModel(dtm(wyd.readPublisher()));
        } catch (Exception ex) {
            Logger.getLogger(PublisherCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addPublisherActionPerformed

    private void recordPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordPublisherActionPerformed
        // TODO add your handling code here:
        try {
            WydawnictwoDAO wyd = new WydawnictwoDAO();
            int selectedRow = publisherTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)publisherTable.getModel();
            int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
            wyd.updatePublisher(id, nameField.getText(), cityField.getText(), regonField.getText(), nipField.getText());
            publisherTable.setModel(dtm(wyd.readPublisher()));
        } catch (Exception ex) {
            Logger.getLogger(PublisherCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordPublisherActionPerformed

    private void deletePublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePublisherActionPerformed
        // TODO add your handling code here:
        try {
            WydawnictwoDAO wyd = new WydawnictwoDAO();
            int selectedRow = publisherTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)publisherTable.getModel();
            int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
            wyd.deletePublisher(id);
            publisherTable.setModel(dtm(wyd.readPublisher()));
        } catch (Exception ex) {
            Logger.getLogger(PublisherCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletePublisherActionPerformed

    private void readPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readPublisherActionPerformed
        // TODO add your handling code here:
        try {
            WydawnictwoDAO wyd = new WydawnictwoDAO();
            publisherTable.setModel(dtm(wyd.readPublisher()));
        } catch (Exception ex) {
            Logger.getLogger(PublisherCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readPublisherActionPerformed

    private void publisherTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publisherTableMouseClicked
        // TODO add your handling code here:
            int selectedRow = publisherTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)publisherTable.getModel();
            String text1 = (String)dt.getValueAt(selectedRow,1);
            String text2 = (String)dt.getValueAt(selectedRow,2);
            String text3 = (String)dt.getValueAt(selectedRow,3);
            String text4 = (String)dt.getValueAt(selectedRow,4);
            
            nameField.setText(text1);
            cityField.setText(text2);
            regonField.setText(text3);
            nipField.setText(text4);
    }//GEN-LAST:event_publisherTableMouseClicked

    private DefaultTableModel dtm(List<Wydawnictwo> wyd){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); 
        String[] propNames = sessionFactory.getClassMetadata(Wydawnictwo.class).getPropertyNames();
        ArrayList<String> arrL = new ArrayList<String>();
        arrL.add(sessionFactory.getClassMetadata(Wydawnictwo.class).getIdentifierPropertyName());
        for(int i=0; i<propNames.length; i++){
            arrL.add(propNames[i]);
        }
        String[] columnNames = arrL.toArray(new String[0]);
        DefaultTableModel tab = new DefaultTableModel(columnNames, 0);
        for(Wydawnictwo w:wyd){
            String[] row = {String.valueOf(w.getId()), w.getNazwa(), w.getMiasto(), w.getREGON(), w.getNIP()};
            tab.addRow(row);
        }
        return tab;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublisherCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublisherCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublisherCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublisherCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublisherCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPublisher;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton deletePublisher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nipField;
    private javax.swing.JLabel nipLabel;
    private javax.swing.JTable publisherTable;
    private javax.swing.JButton readPublisher;
    private javax.swing.JButton recordPublisher;
    private javax.swing.JTextField regonField;
    private javax.swing.JLabel regonLabel;
    // End of variables declaration//GEN-END:variables
}
