/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.crud;
import POJO.Czytelnik;
import dao.CzytelnikDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
/**
 *
 * @author 35747
 */
public class ReaderCreator extends javax.swing.JFrame {

    /**
     * Creates new form categoryCreator
     */
    public ReaderCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        readerTable = new javax.swing.JTable();
        addReader = new javax.swing.JButton();
        recordReader = new javax.swing.JButton();
        deleteReader = new javax.swing.JButton();
        firstName = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        readReader = new javax.swing.JButton();
        secondName = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        secondNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        RoleLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        roleField = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        readerTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
        };
        readerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        readerTable.setColumnSelectionAllowed(true);
        readerTable.setShowGrid(true);
        readerTable.getTableHeader().setReorderingAllowed(false);
        readerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(readerTable);
        readerTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        addReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizard.png"))); // NOI18N
        addReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReaderActionPerformed(evt);
            }
        });

        recordReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support.png"))); // NOI18N
        recordReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordReaderActionPerformed(evt);
            }
        });

        deleteReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        deleteReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReaderActionPerformed(evt);
            }
        });

        firstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstName.setText("Imie");

        firstNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        readReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        readReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readReaderActionPerformed(evt);
            }
        });

        secondName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        secondName.setText("Nazwisko");

        loginField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setText("Hasło");

        login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login.setText("Login");

        addressField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        secondNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setText("Email");

        addressLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addressLabel.setText("ID adresu");

        RoleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoleLabel.setText("ID roli");

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        roleField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(firstName))
                            .addComponent(secondName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondNameField)
                            .addComponent(firstNameField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addReader)
                        .addGap(18, 18, 18)
                        .addComponent(recordReader)
                        .addGap(18, 18, 18)
                        .addComponent(readReader)
                        .addGap(18, 18, 18)
                        .addComponent(deleteReader)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(login)
                            .addComponent(password)
                            .addComponent(email))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordField)
                            .addComponent(loginField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RoleLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roleField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                            .addComponent(addressField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondName)
                    .addComponent(secondNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleLabel)
                    .addComponent(roleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteReader, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addReader)
                            .addComponent(recordReader)))
                    .addComponent(readReader, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReaderActionPerformed
        try {
            if((firstNameField.getText().isEmpty() || secondNameField.getText().isEmpty() || loginField.getText().isEmpty() 
                    || addressField.getText().isEmpty() || passwordField.getText().isEmpty() || addressField.getText().isEmpty() || emailField.getText().isEmpty() || roleField.getText().isEmpty()))
            {
                JOptionPane.showMessageDialog(this, "Pola nie mogą być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }         
            else{
                CzytelnikDAO czytd = new CzytelnikDAO();
                czytd.createReader(firstNameField.getText(), secondNameField.getText(), loginField.getText(), 
                        passwordField.getText(), emailField.getText(), Integer.parseInt(addressField.getText()), 
                        Integer.parseInt(roleField.getText()));
                 readerTable.setModel(dtm(czytd.readReader()));
            }
        } catch (Exception ex) {
            Logger.getLogger(ReaderCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addReaderActionPerformed

    private void recordReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordReaderActionPerformed
        // TODO add your handling code here:
        try {
            if(readerTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go zmodyfikować.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                int selectedRow = readerTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)readerTable.getModel();
                int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                
                CzytelnikDAO czytd = new CzytelnikDAO();
                Czytelnik czyt = czytd.getReader(id);
                
                czytd.updateReader(czyt, firstNameField.getText(), secondNameField.getText(), loginField.getText(), 
                        passwordField.getText(), emailField.getText(), Integer.parseInt(addressField.getText()), 
                        Integer.parseInt(roleField.getText()));
                
                readerTable.setModel(dtm(czytd.readReader()));
            }
        } catch (Exception ex) {
            Logger.getLogger(ReaderCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordReaderActionPerformed

    private void deleteReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReaderActionPerformed
        // TODO add your handling code here:
        try {
            if(readerTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go usunąć.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                CzytelnikDAO czytd = new CzytelnikDAO();
                int selectedRow = readerTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)readerTable.getModel();
                int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                czytd.deleteReader(id);
                readerTable.setModel(dtm(czytd.readReader()));
            }
        } catch (Exception ex) {
            Logger.getLogger(ReaderCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteReaderActionPerformed

    private void readReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readReaderActionPerformed
        // TODO add your handling code here:
        try {
            CzytelnikDAO czytd = new CzytelnikDAO();
            readerTable.setModel(dtm(czytd.readReader()));
        } catch (Exception ex) {
            Logger.getLogger(ReaderCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readReaderActionPerformed

    private void readerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerTableMouseClicked
            // TODO add your handling code here:
            
            
            int selectedRow = readerTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)readerTable.getModel();
            String text1 = (String)dt.getValueAt(selectedRow,1);
            String text2 = (String)dt.getValueAt(selectedRow,2);
            String text3 = (String)dt.getValueAt(selectedRow,3);
            String text4 = (String)dt.getValueAt(selectedRow,4);
            String text5 = (String)dt.getValueAt(selectedRow,5);
            String text6 = (String)dt.getValueAt(selectedRow,6);
            String text7 = (String)dt.getValueAt(selectedRow,7);
            
            
            firstNameField.setText(text1);
            secondNameField.setText(text2);
            loginField.setText(text3);
            passwordField.setText(text4);
            emailField.setText(text5);
            addressField.setText(text6);
            roleField.setText(text7);
            
    }//GEN-LAST:event_readerTableMouseClicked

    private DefaultTableModel dtm(List<Czytelnik> czyt){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); 
        String[] propNames = sessionFactory.getClassMetadata(Czytelnik.class).getPropertyNames();
        ArrayList<String> arrL = new ArrayList<String>();
        arrL.add(sessionFactory.getClassMetadata(Czytelnik.class).getIdentifierPropertyName());
        for(int i=0; i<propNames.length; i++){
            arrL.add(propNames[i]);
        }
        String[] columnNames = arrL.toArray(new String[0]);
        DefaultTableModel tab = new DefaultTableModel(columnNames, 0);
        for(Czytelnik c:czyt){
            String[] row = {String.valueOf(c.getId()), c.getImie(), c.getNazwisko(), c.getLogin(), c.getHaslo(), c.getEmail(),
                    String.valueOf(c.getAdres().getId()), String.valueOf(c.getRola().getId())};
            tab.addRow(row);
        }
        return tab;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReaderCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReaderCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReaderCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReaderCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReaderCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JButton addReader;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton deleteReader;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel login;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel password;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton readReader;
    private javax.swing.JTable readerTable;
    private javax.swing.JButton recordReader;
    private javax.swing.JTextField roleField;
    private javax.swing.JLabel secondName;
    private javax.swing.JTextField secondNameField;
    // End of variables declaration//GEN-END:variables
}
