/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.crud;
import POJO.Rola;
import dao.RolaDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
/**
 *
 * @author 35747
 */
public class RoleCreator extends javax.swing.JFrame {

    /**
     * Creates new form categoryCreator
     */
    public RoleCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        roleTable = new javax.swing.JTable();
        addRole = new javax.swing.JButton();
        recordRole = new javax.swing.JButton();
        deleteRole = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        readRole = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "rola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roleTable.setColumnSelectionAllowed(true);
        roleTable.setShowGrid(true);
        roleTable.getTableHeader().setReorderingAllowed(false);
        roleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(roleTable);
        roleTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (roleTable.getColumnModel().getColumnCount() > 0) {
            roleTable.getColumnModel().getColumn(0).setResizable(false);
            roleTable.getColumnModel().getColumn(1).setResizable(false);
        }

        addRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizard.png"))); // NOI18N
        addRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoleActionPerformed(evt);
            }
        });

        recordRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support.png"))); // NOI18N
        recordRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordRoleActionPerformed(evt);
            }
        });

        deleteRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        deleteRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoleActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setText("Nazwa roli");

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        readRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        readRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addRole)
                        .addGap(18, 18, 18)
                        .addComponent(recordRole)
                        .addGap(18, 18, 18)
                        .addComponent(readRole)
                        .addGap(18, 18, 18)
                        .addComponent(deleteRole)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nameField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteRole, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addRole)
                            .addComponent(recordRole)))
                    .addComponent(readRole, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoleActionPerformed
        try {
            RolaDAO rol = new RolaDAO();
            rol.createRole(nameField.getText());
            roleTable.setModel(dtm(rol.readRole()));
        } catch (Exception ex) {
            Logger.getLogger(RoleCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addRoleActionPerformed

    private void recordRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordRoleActionPerformed
        // TODO add your handling code here:
        try {
            RolaDAO rol = new RolaDAO();
            int selectedRow = roleTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)roleTable.getModel();
            int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
            rol.updateRole(id, nameField.getText());
            roleTable.setModel(dtm(rol.readRole()));
        } catch (Exception ex) {
            Logger.getLogger(RoleCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordRoleActionPerformed

    private void deleteRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoleActionPerformed
        // TODO add your handling code here:
        try {
            RolaDAO rol = new RolaDAO();
            int selectedRow = roleTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)roleTable.getModel();
            int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
            rol.deleteRole(id);
            roleTable.setModel(dtm(rol.readRole()));
        } catch (Exception ex) {
            Logger.getLogger(RoleCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteRoleActionPerformed

    private void readRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readRoleActionPerformed
        // TODO add your handling code here:
        try {
            RolaDAO rol = new RolaDAO();
            roleTable.setModel(dtm(rol.readRole()));
        } catch (Exception ex) {
            Logger.getLogger(RoleCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readRoleActionPerformed

    private void roleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleTableMouseClicked
        // TODO add your handling code here:
            int selectedRow = roleTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)roleTable.getModel();
            String text1 = (String)dt.getValueAt(selectedRow,1);
            nameField.setText(text1);
    }//GEN-LAST:event_roleTableMouseClicked

    private DefaultTableModel dtm(List<Rola> rol){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); 
        String[] propNames = sessionFactory.getClassMetadata(Rola.class).getPropertyNames();
        ArrayList<String> arrL = new ArrayList<String>();
        arrL.add(sessionFactory.getClassMetadata(Rola.class).getIdentifierPropertyName());
        for(int i=0; i<propNames.length; i++){
            arrL.add(propNames[i]);
        }
        String[] columnNames = arrL.toArray(new String[0]);
        DefaultTableModel tab = new DefaultTableModel(columnNames, 0);
        for(Rola r:rol){
            String[] row = {String.valueOf(r.getId()), r.getUserType()};
            tab.addRow(row);
        }
        return tab;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoleCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoleCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoleCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoleCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoleCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRole;
    private javax.swing.JButton deleteRole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton readRole;
    private javax.swing.JButton recordRole;
    private javax.swing.JTable roleTable;
    // End of variables declaration//GEN-END:variables
}
