/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.additional.crud;
import POJO.Autor;
import dao.AutorDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
/**
 *
 * @author 35747
 */
public class AuthorCreator extends javax.swing.JFrame {

    /**
     * Creates new form categoryCreator
     */
    public AuthorCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        authorTable = new javax.swing.JTable();
        addAuthor = new javax.swing.JButton();
        recordAuthor = new javax.swing.JButton();
        deleteAuthor = new javax.swing.JButton();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        readAuthor = new javax.swing.JButton();
        firstNameLabel1 = new javax.swing.JLabel();
        countryField = new javax.swing.JTextField();
        firstNameLabel2 = new javax.swing.JLabel();
        firstNameLabel3 = new javax.swing.JLabel();
        centuryField = new javax.swing.JTextField();
        secondNameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zarządzanie autorami");

        authorTable = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
        };
        authorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        authorTable.setColumnSelectionAllowed(true);
        authorTable.setShowGrid(true);
        authorTable.getTableHeader().setReorderingAllowed(false);
        authorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                authorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(authorTable);
        authorTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        addAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizard.png"))); // NOI18N
        addAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorActionPerformed(evt);
            }
        });

        recordAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support.png"))); // NOI18N
        recordAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordAuthorActionPerformed(evt);
            }
        });

        deleteAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        deleteAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAuthorActionPerformed(evt);
            }
        });

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstNameLabel.setText("Imie");

        firstNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        readAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        readAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAuthorActionPerformed(evt);
            }
        });

        firstNameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstNameLabel1.setText("Nazwisko");

        countryField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        firstNameLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstNameLabel2.setText("Wiek");

        firstNameLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstNameLabel3.setText("Miejsce");

        centuryField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        secondNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel1)
                            .addComponent(firstNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameField)
                            .addComponent(secondNameField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addAuthor)
                        .addGap(18, 18, 18)
                        .addComponent(recordAuthor)
                        .addGap(18, 18, 18)
                        .addComponent(readAuthor)
                        .addGap(18, 18, 18)
                        .addComponent(deleteAuthor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel3)
                            .addComponent(firstNameLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(centuryField)
                            .addComponent(countryField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel1)
                    .addComponent(secondNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel3)
                    .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel2)
                    .addComponent(centuryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAuthor)
                            .addComponent(recordAuthor)))
                    .addComponent(readAuthor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorActionPerformed
        try {
            String first = firstNameField.getText();
            String second = secondNameField.getText();
            String country = countryField.getText();
            String century = centuryField.getText();
            if((first.isEmpty() || second.isEmpty() || country.isEmpty() || century.isEmpty()))
            {
                JOptionPane.showMessageDialog(this, "Pola nie mogą być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if((!Pattern.matches("[A-Z][a-z]*", first) || first.length()>30)){
                JOptionPane.showMessageDialog(this, "Imie musi się składać z pierwszej dużej litery. Długość nie może przekraczać 30.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if((!Pattern.matches("([A-Z][a-z]*-[A-Z][a-z]*|[A-Z][a-z]*)", second) || first.length()>30)){
                JOptionPane.showMessageDialog(this, "Nazwisko musi się składać z pierwszej dużej litery. Długość nie może przekraczać 30.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(country.length()>30){
                JOptionPane.showMessageDialog(this, "Długość nie może przekraczać 30.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if((!Pattern.matches("[A-Z]{1,6}", century))){
                JOptionPane.showMessageDialog(this, "Wiek działania ma zawierać same duże litery i nie może być dłuższy niż 6", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            else{
                AutorDAO aut = new AutorDAO();
                aut.createAuthor(first, second, country, century);
                authorTable.setModel(dtm(aut.readAuthor()));
                setAuthorTableWidth();
            }
        } catch (Exception ex) {
            Logger.getLogger(AuthorCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addAuthorActionPerformed

    private void recordAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordAuthorActionPerformed

        try {
            if(authorTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go zmodyfikować.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                String first = firstNameField.getText();
                String second = secondNameField.getText();
                String country = countryField.getText();
                String century = centuryField.getText();
                if((first.isEmpty() || second.isEmpty() || country.isEmpty() || century.isEmpty()))
                {
                    JOptionPane.showMessageDialog(this, "Pola nie mogą być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else if((!Pattern.matches("[A-Z][a-z]*", first) || first.length()>30)){
                    JOptionPane.showMessageDialog(this, "Imie musi się składać z pierwszej dużej litery. Długość nie może przekraczać 30.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else if((!Pattern.matches("([A-Z][a-z]*-[A-Z][a-z]*|[A-Z][a-z]*)", second) || first.length()>30)){
                    JOptionPane.showMessageDialog(this, "Nazwisko musi się składać z pierwszej dużej litery. Długość nie może przekraczać 30.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else if(country.length()>30 ){
                    JOptionPane.showMessageDialog(this, "Kraj musi się składać z pierwszej dużej litery. Długość nie może przekraczać 30.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else if((!Pattern.matches("[A-Z]{1,6}", century))){
                    JOptionPane.showMessageDialog(this, "Wiek działania ma zawierać same duże litery i nie może być dłuższy niż 6", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else{
                    AutorDAO aut = new AutorDAO();
                    int selectedRow = authorTable.getSelectedRow();
                    DefaultTableModel dt = (DefaultTableModel)authorTable.getModel();
                    int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                    aut.updateAuthor(id, first, second, country, century);
                    authorTable.setModel(dtm(aut.readAuthor()));
                    setAuthorTableWidth();
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(AuthorCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordAuthorActionPerformed

    private void deleteAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAuthorActionPerformed

        try {
            if(authorTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go usunąć.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                AutorDAO aut = new AutorDAO();
                int selectedRow = authorTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)authorTable.getModel();
                int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                aut.deleteAuthor(id);
                authorTable.setModel(dtm(aut.readAuthor()));
                setAuthorTableWidth();  
            }
        } catch (Exception ex) {
            Logger.getLogger(AuthorCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteAuthorActionPerformed

    private void readAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAuthorActionPerformed

        try {
            AutorDAO aut = new AutorDAO();
            authorTable.setModel(dtm(aut.readAuthor()));
            setAuthorTableWidth();
        } catch (Exception ex) {
            Logger.getLogger(AuthorCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readAuthorActionPerformed

    private void authorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorTableMouseClicked

            int selectedRow = authorTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)authorTable.getModel();
            String text1 = (String)dt.getValueAt(selectedRow,1);
            String text2 = (String)dt.getValueAt(selectedRow,2);
            String text3 = (String)dt.getValueAt(selectedRow,3);
            String text4 = (String)dt.getValueAt(selectedRow,4);
            
            firstNameField.setText(text1);
            secondNameField.setText(text2);
            countryField.setText(text3);
            centuryField.setText(text4);
    }//GEN-LAST:event_authorTableMouseClicked

    private DefaultTableModel dtm(List<Autor> aut){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); 
        String[] propNames = sessionFactory.getClassMetadata(Autor.class).getPropertyNames();
        ArrayList<String> arrL = new ArrayList<String>();
        arrL.add(sessionFactory.getClassMetadata(Autor.class).getIdentifierPropertyName());
        for(int i=0; i<propNames.length; i++){
            arrL.add(propNames[i]);
        }
        String[] columnNames = arrL.toArray(new String[0]);
        DefaultTableModel tab = new DefaultTableModel(columnNames, 0);
        for(Autor a:aut){
            String[] row = {String.valueOf(a.getId()), a.getImie(), a.getNazwisko(), a.getMiejsceUrodzenia(), a.getWiekDzialania()};
            tab.addRow(row);
        }
        return tab;
    }
    
    public void setAuthorTableWidth(){
        authorTable.getColumnModel().getColumn(0).setMinWidth(0);
        authorTable.getColumnModel().getColumn(0).setMaxWidth(0);
        authorTable.getColumnModel().getColumn(0).setWidth(0);
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthorCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthorCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthorCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthorCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthorCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAuthor;
    private javax.swing.JTable authorTable;
    private javax.swing.JTextField centuryField;
    private javax.swing.JTextField countryField;
    private javax.swing.JButton deleteAuthor;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JLabel firstNameLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton readAuthor;
    private javax.swing.JButton recordAuthor;
    private javax.swing.JTextField secondNameField;
    // End of variables declaration//GEN-END:variables
}
