/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.additional.crud;
import POJO.Ksiazka;
import dao.KsiazkaDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
/**
 *
 * @author 35747
 */
public class BookCreator extends javax.swing.JFrame {

    /**
     * Creates new form categoryCreator
     */
    public BookCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        addBook = new javax.swing.JButton();
        recordBook = new javax.swing.JButton();
        deleteBook = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        readBook = new javax.swing.JButton();
        description = new javax.swing.JLabel();
        yearOfReleaseTitle = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        yearOfRelease = new javax.swing.JLabel();
        authorField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        categoryField = new javax.swing.JTextField();
        publisherField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionField = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
        };
        bookTable.setColumnSelectionAllowed(true);
        bookTable.setShowGrid(true);
        bookTable.getTableHeader().setReorderingAllowed(false);
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);
        bookTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        addBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizard.png"))); // NOI18N
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        recordBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support.png"))); // NOI18N
        recordBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBookActionPerformed(evt);
            }
        });

        deleteBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        deleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title.setText("Tytuł");

        titleField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        readBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        readBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBookActionPerformed(evt);
            }
        });

        description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        description.setText("Opis");

        yearOfReleaseTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price.setText("Cena biblioteki");

        yearOfRelease.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yearOfRelease.setText("Rok wydania");

        authorField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        priceField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        categoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        categoryLabel.setText("ID kategorii");

        authorLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        authorLabel.setText("ID autora");

        publisherLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        publisherLabel.setText("ID wydawnictwa");

        categoryField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        publisherField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        descriptionField.setColumns(20);
        descriptionField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionField.setRows(5);
        jScrollPane2.setViewportView(descriptionField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(description)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(title)
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleField)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBook)
                        .addGap(18, 18, 18)
                        .addComponent(recordBook)
                        .addGap(18, 18, 18)
                        .addComponent(readBook)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBook)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yearOfRelease)
                            .addComponent(price)
                            .addComponent(categoryLabel)
                            .addComponent(authorLabel)
                            .addComponent(publisherLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categoryField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(priceField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(publisherField)
                            .addComponent(yearOfReleaseTitle, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearOfRelease)
                    .addComponent(yearOfReleaseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLabel)
                    .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publisherLabel)
                    .addComponent(publisherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteBook, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBook)
                            .addComponent(recordBook)))
                    .addComponent(readBook, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        try {
            if((titleField.getText().isEmpty() || descriptionField.getText().isEmpty() || yearOfReleaseTitle.getText().isEmpty() 
                    || authorField.getText().isEmpty() || priceField.getText().isEmpty() || authorField.getText().isEmpty() || categoryField.getText().isEmpty() || publisherField.getText().isEmpty()))
            {
                JOptionPane.showMessageDialog(this, "Pola nie mogą być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }         
            else{
                KsiazkaDAO ksid = new KsiazkaDAO();
                ksid.createBook(titleField.getText(), descriptionField.getText(), Integer.parseInt(yearOfReleaseTitle.getText()), 
                        Double.parseDouble(priceField.getText()), Integer.parseInt(categoryField.getText()), Integer.parseInt(authorField.getText()), 
                        Integer.parseInt(publisherField.getText()));
                 bookTable.setModel(dtm(ksid.readBook()));
            }
        } catch (Exception ex) {
            Logger.getLogger(BookCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBookActionPerformed

    private void recordBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBookActionPerformed
        // TODO add your handling code here:
        try {
            if(bookTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go zmodyfikować.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                int selectedRow = bookTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)bookTable.getModel();
                String title = dt.getValueAt(selectedRow, 1).toString();
                
                KsiazkaDAO ksid = new KsiazkaDAO();
                Ksiazka ksi = ksid.getBook(title);
                
                ksid.updateBook(ksi, titleField.getText(), descriptionField.getText(), Integer.parseInt(yearOfReleaseTitle.getText()), 
                        Double.parseDouble(priceField.getText()), Integer.parseInt(categoryField.getText()), Integer.parseInt(authorField.getText()), 
                        Integer.parseInt(publisherField.getText()));
                
                bookTable.setModel(dtm(ksid.readBook()));
            }
        } catch (Exception ex) {
            Logger.getLogger(BookCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordBookActionPerformed

    private void deleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookActionPerformed
        // TODO add your handling code here:
        try {
            if(bookTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go usunąć.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                KsiazkaDAO ksid = new KsiazkaDAO();
                int selectedRow = bookTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)bookTable.getModel();
                int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                ksid.deleteBook(id);
                bookTable.setModel(dtm(ksid.readBook()));
            }
        } catch (Exception ex) {
            Logger.getLogger(BookCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBookActionPerformed

    private void readBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBookActionPerformed
        // TODO add your handling code here:
        try {
            KsiazkaDAO ksid = new KsiazkaDAO();
            bookTable.setModel(dtm(ksid.readBook()));
        } catch (Exception ex) {
            Logger.getLogger(BookCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readBookActionPerformed

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
            // TODO add your handling code here:
            
            
            int selectedRow = bookTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)bookTable.getModel();
            String text1 = (String)dt.getValueAt(selectedRow,1);
            String text2 = (String)dt.getValueAt(selectedRow,2);
            String text3 = (String)dt.getValueAt(selectedRow,3);
            String text4 = (String)dt.getValueAt(selectedRow,4);
            String text5 = (String)dt.getValueAt(selectedRow,5);
            String text6 = (String)dt.getValueAt(selectedRow,6);
            String text7 = (String)dt.getValueAt(selectedRow,7);
            
            
            titleField.setText(text1);
            descriptionField.setText(text2);
            yearOfReleaseTitle.setText(text3);
            priceField.setText(text4);
            categoryField.setText(text5);
            authorField.setText(text6);
            publisherField.setText(text7);
            
    }//GEN-LAST:event_bookTableMouseClicked

    private DefaultTableModel dtm(List<Ksiazka> ksi){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); 
        String[] propNames = sessionFactory.getClassMetadata(Ksiazka.class).getPropertyNames();
        ArrayList<String> arrL = new ArrayList<String>();
        arrL.add(sessionFactory.getClassMetadata(Ksiazka.class).getIdentifierPropertyName());
        for(int i=0; i<propNames.length; i++){
            arrL.add(propNames[i]);
        }
        String[] columnNames = arrL.toArray(new String[0]);
        DefaultTableModel tab = new DefaultTableModel(columnNames, 0);
        for(Ksiazka k:ksi){
            String[] row = {String.valueOf(k.getId()), k.getTytuł(), k.getOpis(), String.valueOf(k.getRokWydania()), String.valueOf(k.getCenaBiblioteki()), String.valueOf(k.getKategoria().getId()), 
                    String.valueOf(k.getAutor().getId()), String.valueOf(k.getWydawnictwo().getId())};
            tab.addRow(row);
        }
        return tab;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JTextField authorField;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTable bookTable;
    private javax.swing.JTextField categoryField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton deleteBook;
    private javax.swing.JLabel description;
    private javax.swing.JTextArea descriptionField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel price;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField publisherField;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JButton readBook;
    private javax.swing.JButton recordBook;
    private javax.swing.JLabel title;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel yearOfRelease;
    private javax.swing.JTextField yearOfReleaseTitle;
    // End of variables declaration//GEN-END:variables
}
