/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.additional.crud;
import POJO.Kategoria;
import dao.KategoriaDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
/**
 *
 * @author 35747
 */
public class CategoryCreator extends javax.swing.JFrame {

    /**
     * Creates new form categoryCreator
     */
    public CategoryCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        addCategory = new javax.swing.JButton();
        recordCategory = new javax.swing.JButton();
        deleteCategory = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        readButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zarządzanie kategoriami");

        categoryTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
        };
        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        categoryTable.setColumnSelectionAllowed(true);
        categoryTable.setShowGrid(true);
        categoryTable.getTableHeader().setReorderingAllowed(false);
        categoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(categoryTable);
        categoryTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        addCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizard.png"))); // NOI18N
        addCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryActionPerformed(evt);
            }
        });

        recordCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support.png"))); // NOI18N
        recordCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordCategoryActionPerformed(evt);
            }
        });

        deleteCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        deleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCategoryActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setText("Nazwa kategorii");

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        readButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        readButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCategory)
                        .addGap(18, 18, 18)
                        .addComponent(recordCategory)
                        .addGap(18, 18, 18)
                        .addComponent(readButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCategory)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCategory)
                            .addComponent(recordCategory)))
                    .addComponent(readButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryActionPerformed
        try {
            String nf = nameField.getText();
            if(nf.isEmpty()){
                JOptionPane.showMessageDialog(this, "Pola nie mogą być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if((!Pattern.matches("([A-Z][a-z]*|[A-Z][a-z]*-[A-Z][a-z]*|[a-zA-Z]* [a-zA-Z]*)", nf) || nf.length()>50)){
                    JOptionPane.showMessageDialog(this, "Nazwa kategorii musi zawierać tylko litery. Musi się zaczynać od dużej litery. Długość ma nie przekraczać 50 znaków.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
            KategoriaDAO kat = new KategoriaDAO();
            kat.createCategory(nf);
            categoryTable.setModel(dtm(kat.readCategory()));
            setCategoryTableWidth();
            }
        } catch (Exception ex) {
            Logger.getLogger(CategoryCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addCategoryActionPerformed

    private void recordCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordCategoryActionPerformed

        try {
            String nf = nameField.getText();
            if(categoryTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go zmodyfikować.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                if(nf.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Pola nie mogą być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else if((!Pattern.matches("([A-Z][a-z]*|[A-Z][a-z]*-[A-Z][a-z]*|[a-zA-Z]* [a-zA-Z]*)", nf) || nf.length()>50)){
                        JOptionPane.showMessageDialog(this, "Nazwa kategorii musi zawierać tylko litery. Musi się zaczynać od dużej litery. Długość ma nie przekraczać 50 znaków.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else{
                    KategoriaDAO kat = new KategoriaDAO();
                    int selectedRow = categoryTable.getSelectedRow();
                    DefaultTableModel dt = (DefaultTableModel)categoryTable.getModel();
                    int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                    kat.updateCategory(id, nameField.getText());
                    categoryTable.setModel(dtm(kat.readCategory()));
                    setCategoryTableWidth();
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(CategoryCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordCategoryActionPerformed

    private void deleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCategoryActionPerformed

        try {
            if(categoryTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go usunąć.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                KategoriaDAO kat = new KategoriaDAO();
                int selectedRow = categoryTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)categoryTable.getModel();
                int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                kat.deleteCategory(id);
                categoryTable.setModel(dtm(kat.readCategory()));
                setCategoryTableWidth();
            }
        } catch (Exception ex) {
            Logger.getLogger(CategoryCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteCategoryActionPerformed

    private void readButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonActionPerformed

        try {
            KategoriaDAO kat = new KategoriaDAO();
            categoryTable.setModel(dtm(kat.readCategory()));
            setCategoryTableWidth();
        } catch (Exception ex) {
            Logger.getLogger(CategoryCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readButtonActionPerformed

    private void categoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryTableMouseClicked

            int selectedRow = categoryTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)categoryTable.getModel();
            String text1 = (String)dt.getValueAt(selectedRow,1);
            nameField.setText(text1);
    }//GEN-LAST:event_categoryTableMouseClicked

    private DefaultTableModel dtm(List<Kategoria> kat){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); 
        String[] propNames = sessionFactory.getClassMetadata(Kategoria.class).getPropertyNames();
        ArrayList<String> arrL = new ArrayList<String>();
        arrL.add(sessionFactory.getClassMetadata(Kategoria.class).getIdentifierPropertyName());
        for(int i=0; i<propNames.length; i++){
            arrL.add(propNames[i]);
        }
        String[] columnNames = arrL.toArray(new String[0]);
        DefaultTableModel tab = new DefaultTableModel(columnNames, 0);
        for(Kategoria k:kat){
            String[] row = {String.valueOf(k.getId()), k.getNazwa()};
            tab.addRow(row);
        }
        return tab;
    }
    
    public void setCategoryTableWidth(){
        categoryTable.getColumnModel().getColumn(0).setMinWidth(0);
        categoryTable.getColumnModel().getColumn(0).setMaxWidth(0);
        categoryTable.getColumnModel().getColumn(0).setWidth(0);
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategory;
    private javax.swing.JTable categoryTable;
    private javax.swing.JButton deleteCategory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton readButton;
    private javax.swing.JButton recordCategory;
    // End of variables declaration//GEN-END:variables
}
