/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.additional.crud;
import POJO.Czytelnik;
import POJO.Egzemplarz;
import POJO.Wypozyczenia;
import dao.WypożyczenieDAO;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
/**
 *
 * @author 35747
 */
public class LendCreator extends javax.swing.JFrame {

    /**
     * Creates new form categoryCreator
     */
    public LendCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        lendTable = new javax.swing.JTable();
        addLend = new javax.swing.JButton();
        recordLend = new javax.swing.JButton();
        deleteLend = new javax.swing.JButton();
        reader = new javax.swing.JLabel();
        readLend = new javax.swing.JButton();
        piece = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        lendDateField = new javax.swing.JTextField();
        returnDateField = new javax.swing.JTextField();
        lendDate = new javax.swing.JLabel();
        returnDate = new javax.swing.JLabel();
        penalty = new javax.swing.JLabel();
        penaltyField = new javax.swing.JTextField();
        returnField = new javax.swing.JTextField();
        returnLabel = new javax.swing.JLabel();
        readerBox = new javax.swing.JComboBox<>();
        pieceBox = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zarządzanie wypożyczeniami");

        lendTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
        };
        lendTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        lendTable.setColumnSelectionAllowed(true);
        lendTable.setShowGrid(true);
        lendTable.getTableHeader().setReorderingAllowed(false);
        lendTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lendTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lendTable);
        lendTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        addLend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizard.png"))); // NOI18N
        addLend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLendActionPerformed(evt);
            }
        });

        recordLend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support.png"))); // NOI18N
        recordLend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordLendActionPerformed(evt);
            }
        });

        deleteLend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        deleteLend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLendActionPerformed(evt);
            }
        });

        reader.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reader.setText("czytelnik");

        readLend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        readLend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readLendActionPerformed(evt);
            }
        });

        piece.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        piece.setText("egzemplarz");

        login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lendDateField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        returnDateField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lendDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lendDate.setText("data_wypozyczenia");

        returnDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnDate.setText("data_oddania");

        penalty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        penalty.setText("kara");

        penaltyField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        returnField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        returnLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnLabel.setText("oddane");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addLend)
                        .addGap(18, 18, 18)
                        .addComponent(recordLend)
                        .addGap(18, 18, 18)
                        .addComponent(readLend)
                        .addGap(18, 18, 18)
                        .addComponent(deleteLend)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(login)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(penalty))
                            .addComponent(reader, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(piece, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(returnDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lendDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(returnLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(returnDateField)
                            .addComponent(lendDateField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(penaltyField)
                            .addComponent(readerBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pieceBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reader)
                    .addComponent(readerBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piece)
                    .addComponent(pieceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lendDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lendDate))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(login))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnDate)
                            .addComponent(returnDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(penalty)
                            .addComponent(penaltyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteLend, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addLend)
                            .addComponent(recordLend)))
                    .addComponent(readLend, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addLendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLendActionPerformed
        try {
            String ld = lendDateField.getText();
            String rd = returnDateField.getText();
            String pf = penaltyField.getText();
            String rf = returnField.getText();
            if((ld.isEmpty() || pf.isEmpty() || rf.isEmpty()))
            {
                JOptionPane.showMessageDialog(this, "Tylko pole oddania może być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            else if(!Pattern.matches("[0-9]{4}-[0-9]{2}-[0-9]{2}", ld)){
                JOptionPane.showMessageDialog(this, "Data wypożyczenia musi mieć format RRRR-MM-DD", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(!Pattern.matches("[0-9]*.[0-9]{1,2}", pf))
            {
                JOptionPane.showMessageDialog(this, "Kara musi mieć część groszową", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(!Pattern.matches("true|false", rf)){
                JOptionPane.showMessageDialog(this, "Oddanie musi być równe false albo true.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if((!rd.isEmpty() && !Pattern.matches("[0-9]{4}-[0-9]{2}-[0-9]{2}", rd))){
                JOptionPane.showMessageDialog(this, "Data oddania musi mieć format RRRR-MM-DD", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            else{
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                WypożyczenieDAO wypozyczenied = new WypożyczenieDAO();
                
                Czytelnik c = (Czytelnik) readerBox.getSelectedItem();
                Egzemplarz e = (Egzemplarz) pieceBox.getSelectedItem();
                
                Date returnDate;
                if(rd.isEmpty()){
                    returnDate = null;
                }else{
                returnDate = formatter.parse(rd);
                }
                
                wypozyczenied.createLendAdmin(formatter.parse(ld), returnDate, Double.parseDouble(pf),c.getId(), e.getId(), Boolean.parseBoolean(rf));
                lendTable.setModel(dtm(wypozyczenied.readLend()));
                setLendTableWidth();
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_addLendActionPerformed

    private void recordLendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordLendActionPerformed

        try {
            if(lendTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go zmodyfikować.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                String ld = lendDateField.getText();
                String rd = returnDateField.getText();
                String pf = penaltyField.getText();
                String rf = returnField.getText();
                if((ld.isEmpty() || pf.isEmpty() || rf.isEmpty()))
                {
                    JOptionPane.showMessageDialog(this, "Tylko pole oddania może być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
                else if(!Pattern.matches("[0-9]{4}-[0-9]{2}-[0-9]{2}", ld)){
                    JOptionPane.showMessageDialog(this, "Data wypożyczenia musi mieć format RRRR-MM-DD", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else if(!Pattern.matches("[0-9]*.[0-9]{1,2}", pf))
                {
                    JOptionPane.showMessageDialog(this, "Kara musi mieć część groszową", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else if(!Pattern.matches("true|false", rf)){
                    JOptionPane.showMessageDialog(this, "Oddanie musi być równe false albo true.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else if((!rd.isEmpty() && !Pattern.matches("[0-9]{4}-[0-9]{2}-[0-9]{2}", rd))){
                    JOptionPane.showMessageDialog(this, "Data oddania musi mieć format RRRR-MM-DD", "ERROR", JOptionPane.WARNING_MESSAGE);
                } 
                else{
                    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                    int selectedRow = lendTable.getSelectedRow();
                    DefaultTableModel dt = (DefaultTableModel)lendTable.getModel();
                    int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());

                    WypożyczenieDAO wypozyczenied = new WypożyczenieDAO();
                    Wypozyczenia wypozyczenie = wypozyczenied.getLend(id);
                    Czytelnik c = (Czytelnik) readerBox.getSelectedItem();
                    Egzemplarz e = (Egzemplarz) pieceBox.getSelectedItem();
                    Date returnDate;
                    if(rd.isEmpty()){
                        returnDate = null;
                    }else{
                    returnDate = formatter.parse(rd);
                    }
                    wypozyczenied.updateLend(wypozyczenie, formatter.parse(ld), returnDate, Double.parseDouble(pf),c.getId(), e.getId(), Boolean.parseBoolean(rf));

                    lendTable.setModel(dtm(wypozyczenied.readLend()));
                    setLendTableWidth();
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(LendCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordLendActionPerformed

    private void deleteLendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLendActionPerformed

        try {
            if(lendTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go usunąć.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                WypożyczenieDAO wypozyczenied = new WypożyczenieDAO();
                int selectedRow = lendTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)lendTable.getModel();
                int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                wypozyczenied.deleteLend(id);
                lendTable.setModel(dtm(wypozyczenied.readLend()));
                setLendTableWidth();
            }
        } catch (Exception ex) {
            Logger.getLogger(LendCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteLendActionPerformed

    private void readLendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readLendActionPerformed

        try {
            WypożyczenieDAO wypozyczenied = new WypożyczenieDAO();
            lendTable.setModel(dtm(wypozyczenied.readLend()));
            setLendTableWidth();
        } catch (Exception ex) {
            Logger.getLogger(LendCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readLendActionPerformed

    private void lendTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lendTableMouseClicked
            
            int selectedRow = lendTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)lendTable.getModel();
            String text1 = (String)dt.getValueAt(selectedRow,1);
            String text2 = (String)dt.getValueAt(selectedRow,2);
            String text3 = (String)dt.getValueAt(selectedRow,3);
                        
            lendDateField.setText(text1);
            returnDateField.setText(text2);
            penaltyField.setText(text3);
    }//GEN-LAST:event_lendTableMouseClicked

    private DefaultTableModel dtm(List<Wypozyczenia> wyp){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); 
        String[] propNames = sessionFactory.getClassMetadata(Wypozyczenia.class).getPropertyNames();
        ArrayList<String> arrL = new ArrayList<String>();
        arrL.add(sessionFactory.getClassMetadata(Wypozyczenia.class).getIdentifierPropertyName());
        for(int i=0; i<propNames.length; i++){
            arrL.add(propNames[i]);
        }
        String[] columnNames = arrL.toArray(new String[0]);
        DefaultTableModel tab = new DefaultTableModel(columnNames, 0);
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        for(Wypozyczenia w:wyp){
            String oddane;
            if(w.getOddane()==true){
                oddane = "Tak";
            }else{
                oddane = "Nie";
            }
            String returnDate;
            if(w.getData_oddania()==null){
                returnDate = null;
            }else{
                returnDate = formatter.format(w.getData_oddania());
            }
            String[] row = {String.valueOf(w.getId()),String.valueOf(formatter.format(w.getData_wypozyczenia())), returnDate, 
                String.valueOf(w.getKara()),String.valueOf(w.getEgzemplarz().getKsiazka().getTytuł()),
                String.valueOf(w.getCzytelnik().getImie()+ " " +w.getCzytelnik().getNazwisko()),oddane};
            tab.addRow(row);
        }
        return tab;
    }
    
    public JComboBox getPieceBox() {
        return pieceBox;
    }

    public JComboBox getReaderBox() {
        return readerBox;
    }
    
    public void setLendTableWidth(){
        lendTable.getColumnModel().getColumn(0).setMinWidth(0);
        lendTable.getColumnModel().getColumn(0).setMaxWidth(0);
        lendTable.getColumnModel().getColumn(0).setWidth(0);
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LendCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LendCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LendCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LendCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LendCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLend;
    private javax.swing.JButton deleteLend;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lendDate;
    private javax.swing.JTextField lendDateField;
    private javax.swing.JTable lendTable;
    private javax.swing.JLabel login;
    private javax.swing.JLabel penalty;
    private javax.swing.JTextField penaltyField;
    private javax.swing.JLabel piece;
    private javax.swing.JComboBox<String> pieceBox;
    private javax.swing.JButton readLend;
    private javax.swing.JLabel reader;
    private javax.swing.JComboBox<String> readerBox;
    private javax.swing.JButton recordLend;
    private javax.swing.JLabel returnDate;
    private javax.swing.JTextField returnDateField;
    private javax.swing.JTextField returnField;
    private javax.swing.JLabel returnLabel;
    // End of variables declaration//GEN-END:variables
}
