/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.additional.crud;
import POJO.Adres;
import POJO.Czytelnik;
import POJO.Rola;
import dao.CzytelnikDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
/**
 *
 * @author 35747
 */
public class ReaderCreator extends javax.swing.JFrame {

    /**
     * Creates new form categoryCreator
     */
    public ReaderCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        readerTable = new javax.swing.JTable();
        addReader = new javax.swing.JButton();
        recordReader = new javax.swing.JButton();
        deleteReader = new javax.swing.JButton();
        firstName = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        readReader = new javax.swing.JButton();
        secondName = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        secondNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        RoleLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        addressBox = new javax.swing.JComboBox<>();
        roleBox = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zarządzanie czytelnikami");

        readerTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
        };
        readerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        readerTable.setColumnSelectionAllowed(true);
        readerTable.setShowGrid(true);
        readerTable.getTableHeader().setReorderingAllowed(false);
        readerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(readerTable);
        readerTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        addReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizard.png"))); // NOI18N
        addReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReaderActionPerformed(evt);
            }
        });

        recordReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support.png"))); // NOI18N
        recordReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordReaderActionPerformed(evt);
            }
        });

        deleteReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        deleteReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReaderActionPerformed(evt);
            }
        });

        firstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstName.setText("Imie");

        firstNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        readReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        readReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readReaderActionPerformed(evt);
            }
        });

        secondName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        secondName.setText("Nazwisko");

        loginField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setText("Hasło");

        login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login.setText("Login");

        secondNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setText("Email");

        addressLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addressLabel.setText("Adres");

        RoleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoleLabel.setText("Rola");

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(firstName))
                            .addComponent(secondName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondNameField)
                            .addComponent(firstNameField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addReader)
                        .addGap(18, 18, 18)
                        .addComponent(recordReader)
                        .addGap(18, 18, 18)
                        .addComponent(readReader)
                        .addGap(18, 18, 18)
                        .addComponent(deleteReader)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RoleLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(password)
                                    .addComponent(login))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(roleBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondName)
                    .addComponent(secondNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleLabel)
                    .addComponent(roleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteReader, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addReader)
                            .addComponent(recordReader)))
                    .addComponent(readReader, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReaderActionPerformed
        try {
            String fn = firstNameField.getText();
            String sn = secondNameField.getText();
            String lf = loginField.getText();
            String pf = passwordField.getText();
            String ef = emailField.getText();
            CzytelnikDAO czytd = new CzytelnikDAO();  
            if((fn.isEmpty() || sn.isEmpty() || lf.isEmpty() || pf.isEmpty() || ef.isEmpty()))
            {
                JOptionPane.showMessageDialog(this, "Pola nie mogą być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            else if((lf.length() > 30 || lf.length() < 8 || pf.length() > 30 || pf.length() < 8)){
                JOptionPane.showMessageDialog(this, "Login i hasło powinny mieć od 8 do 30 znaków !!!", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            else if((!Pattern.matches("([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$",  ef) || ef.length() > 255))
            {
                JOptionPane.showMessageDialog(this, "Email powinen być w dobrej formie i mieć nie więcej niż 255 znaków.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            else if((fn.length() > 30 || sn.length() > 30 || !Pattern.matches("[a-zA-Z]*", fn) || !Pattern.matches("([A-Z][a-z]*-[A-Z][a-z]*|[A-Z][a-z]*)", sn))){
                JOptionPane.showMessageDialog(this, "Długość imienia i nazwiska nie może być dłuższa niż 30 liter. Musi się zaczynać z dużej litery.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(czytd.emailExist(ef)){
                JOptionPane.showMessageDialog(this, "Email istnieje juz w bazie.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(czytd.readerExist(lf)){
                JOptionPane.showMessageDialog(this, "Login istnieje już w bazie.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{   
                Adres a = (Adres) addressBox.getSelectedItem();
                Rola r = (Rola) roleBox.getSelectedItem();
         
                czytd.createReader(fn, sn, lf,pf, ef, a.getId(), r.getId());
                 readerTable.setModel(dtm(czytd.readReader()));
                 setReaderTableWidth();
            }
        } catch (Exception ex) {
            Logger.getLogger(ReaderCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addReaderActionPerformed

    private void recordReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordReaderActionPerformed

        try {
            if(readerTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go zmodyfikować.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                String fn = firstNameField.getText();
                String sn = secondNameField.getText();
                String lf = loginField.getText();
                String pf = passwordField.getText();
                String ef = emailField.getText();
                CzytelnikDAO czytd = new CzytelnikDAO();  
                if((fn.isEmpty() || sn.isEmpty() || lf.isEmpty() || pf.isEmpty() || ef.isEmpty()))
                {
                    JOptionPane.showMessageDialog(this, "Pola nie mogą być puste.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
                else if((lf.length() > 30 || lf.length() < 8 || pf.length() > 30 || pf.length() < 8)){
                    JOptionPane.showMessageDialog(this, "Login i hasło powinny mieć od 8 do 30 znaków !!!", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
                else if((!Pattern.matches("([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$",  ef) || ef.length() > 255))
                {
                    JOptionPane.showMessageDialog(this, "Email powinen być w dobrej formie i mieć nie więcej niż 255 znaków.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
                else if((fn.length() > 30 || sn.length() > 30 || !Pattern.matches("[a-zA-Z]*", fn) || !Pattern.matches("([A-Z][a-z]*-[A-Z][a-z]*|[A-Z][a-z]*)", sn))){
                    JOptionPane.showMessageDialog(this, "Długość imienia i nazwiska nie może być dłuższa niż 30 liter. Musi się zaczynać z dużej litery.", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else{   
                    int selectedRow = readerTable.getSelectedRow();
                    DefaultTableModel dt = (DefaultTableModel)readerTable.getModel();
                    int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());

                    Czytelnik czyt = czytd.getReader(id);

                    Adres a = (Adres) addressBox.getSelectedItem();
                    Rola r = (Rola) roleBox.getSelectedItem();
                    czytd.updateReader(czyt, fn, sn, lf,pf, ef, a.getId(), r.getId());

                    readerTable.setModel(dtm(czytd.readReader()));
                    setReaderTableWidth();
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ReaderCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordReaderActionPerformed

    private void deleteReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReaderActionPerformed

        try {
            if(readerTable.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Musisz zaznaczyć rekord, aby go usunąć.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                CzytelnikDAO czytd = new CzytelnikDAO();
                int selectedRow = readerTable.getSelectedRow();
                DefaultTableModel dt = (DefaultTableModel)readerTable.getModel();
                int id = Integer.parseInt(dt.getValueAt(selectedRow, 0).toString());
                czytd.deleteReader(id);
                readerTable.setModel(dtm(czytd.readReader()));
                setReaderTableWidth();
            }
        } catch (Exception ex) {
            Logger.getLogger(ReaderCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteReaderActionPerformed

    private void readReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readReaderActionPerformed

        try {
            CzytelnikDAO czytd = new CzytelnikDAO();
            readerTable.setModel(dtm(czytd.readReader()));
            setReaderTableWidth();
        } catch (Exception ex) {
            Logger.getLogger(ReaderCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readReaderActionPerformed

    private void readerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerTableMouseClicked

            int selectedRow = readerTable.getSelectedRow();
            DefaultTableModel dt = (DefaultTableModel)readerTable.getModel();
            String text1 = (String)dt.getValueAt(selectedRow,1);
            String text2 = (String)dt.getValueAt(selectedRow,2);
            String text3 = (String)dt.getValueAt(selectedRow,3);
            String text4 = (String)dt.getValueAt(selectedRow,4);
            String text5 = (String)dt.getValueAt(selectedRow,5);
              
            firstNameField.setText(text1);
            secondNameField.setText(text2);
            loginField.setText(text3);
            passwordField.setText(text4);
            emailField.setText(text5);
    }//GEN-LAST:event_readerTableMouseClicked

    private DefaultTableModel dtm(List<Czytelnik> czyt){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory(); 
        String[] propNames = sessionFactory.getClassMetadata(Czytelnik.class).getPropertyNames();
        ArrayList<String> arrL = new ArrayList<String>();
        arrL.add(sessionFactory.getClassMetadata(Czytelnik.class).getIdentifierPropertyName());
        for(int i=0; i<propNames.length; i++){
            arrL.add(propNames[i]);
        }
        String[] columnNames = arrL.toArray(new String[0]);
        DefaultTableModel tab = new DefaultTableModel(columnNames, 0);
        for(Czytelnik c:czyt){
            String[] row = {String.valueOf(c.getId()), c.getImie(), c.getNazwisko(), c.getLogin(), c.getHaslo(), c.getEmail(),
                    String.valueOf(c.getAdres().getMiasto()+ " " + c.getAdres().getUlica() + " " + c.getAdres().getNumerDomu()), String.valueOf(c.getRola().getUserType())};
            tab.addRow(row);
        }
        return tab;
    }
    
    public void setReaderTableWidth(){
        readerTable.getColumnModel().getColumn(0).setMinWidth(0);
        readerTable.getColumnModel().getColumn(0).setMaxWidth(0);
        readerTable.getColumnModel().getColumn(0).setWidth(0);
    }   

    public JComboBox getAddressBox() {
        return addressBox;
    }

    public JComboBox getRoleBox() {
        return roleBox;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReaderCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReaderCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReaderCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReaderCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReaderCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JButton addReader;
    private javax.swing.JComboBox<String> addressBox;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton deleteReader;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel login;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel password;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton readReader;
    private javax.swing.JTable readerTable;
    private javax.swing.JButton recordReader;
    private javax.swing.JComboBox<String> roleBox;
    private javax.swing.JLabel secondName;
    private javax.swing.JTextField secondNameField;
    // End of variables declaration//GEN-END:variables
}
